### ISSUE TITLE
Command and configs

### ISSUE THREAD

**Issue by ElviraLL** [budiu-39/interaction_AMP#2]
Nice work! Can you provide the command you used for training and inference? Like which configuration you used, Thanks!

**Comment by budiu-39** [comment]
Since this repo is a implement of [Synthesizing Physical Character-Scene Interactions](https://xbpeng.github.io/projects/InterPhys/index.html). The code is based on [ASE](https://github.com/nv-tlabs/ASE/).  
The format of command to train/test the code:   
python ase/run.py --task HumanoidAMPObject --cfg_env ase/data/cfg/humanoid_amp.yaml --cfg_train ase/data/cfg/train/rlg/amp_humanoid.yaml --motion_file ase/data/motions/chair_cut --headless
For more details, you might need to dive into the code. Since this is my first repo, I didn't build and record it very well qaq. 
This code is trainable and testable, since motion dataset and checkpoint are uploaded.
Btw I found I make a small mistake by uploading the code. I fix it already.

**Comment by ElviraLL** [comment]
Thanks! Did you made any modifications on the environment and training configuraion yaml files? I didn't find `humanoid_amp.yaml` from your codebase. Can I use the original yaml file from the ASE repo? I assume that you would made some modificatoins for the objects?

**Comment by ElviraLL** [comment]
The repo is also missing `amp_humanoid_smplx_male.xml` file for humanoid

**Comment by budiu-39** [comment]
I think the configuration file should be "humanoid_location_scene.yaml"
The humanoid model file can be "amp_humanoid.xml" or any other humanoid model you like.

**Comment by ElviraLL** [comment]
Thanks! 
I met an error when loading the assets
```
[Error] [carb.gym.plugin] *** Failed to load 'data/assets/mjcf/amp_humanoid.xml'
[Error] [carb.gym.plugin] *** Failed to load 'amp_humanoid.xml' from 'data/assets/mjcf'
*** Failed to load 'data/assets/objects/0f25a699-6560-426d-a590-7e69986c449d.urdf'[Error] [carb.gym.plugin] Failed to parse URDF file 'objects/0f25a699-6560-426d-a590-7e69986c449d.urdf'
[Error] [carb.gym.plugin] Failed to import URDF file 'objects/0f25a699-6560-426d-a590-7e69986c449d.urdf'
[Error] [carb.gym.plugin] *** Failed to load 'objects/0f25a699-6560-426d-a590-7e69986c449d.urdf' from 'data/assets'
```
Isaac didn't provide any hint on what's goind on with the file. Have you ever seens this before?
